GET localhost:8080/api/v1/task/list

### get by id
GET localhost:8080/api/v1/task/8

### create task
POST localhost:8080/api/v1/task/
Content-Type: application/json

{
  "name": "do anything 2",
  "isCompleted": true
}


###UPDATE task
PUT localhost:8080/api/v1/task/
Content-Type: application/json

{
  "name": "do anything"
}


### DELETE REQUEST


DELETE localhost:8080/api/v1/task/4


###